### ISSUE TITLE
4.3 BPE算法代码

### ISSUE THREAD

**Issue by nanocm** [LLMBook-zh/LLMBook-zh.github.io#10]
4.3的BPE算法的python代码有一些误导性的注释和变量命名，请重新审查一下
例如extract_frequencies的sequence以及encode_with_bpe的texts应该是语料单词的列表: list[word]，或者在代码部分添加一个具体的data的值

**Comment by leoleojie** [comment]
非常感谢您的建议，我们会修改代码
