### ISSUE TITLE
[Suggestion] 4.4.1 数据混合能否加上「数据调度方式」的段落

### ISSUE THREAD

**Issue by rgtjf** [LLMBook-zh/LLMBook-zh.github.io#13]
这[这篇技术报告](https://arxiv.org/abs/2404.15702)里，指出了在线数据调度的方式。传统的离线数据调度是将数据离线转换为词元，创建相应的数据集索引。在线数据调度集成了在线数据流和数据调度器，能够实现动态的数据调整和训练过程中的反馈优化。

为了进一步说明这一点，可以参考下图（来源：[data-flow.pdf](https://github.com/LLMBook-zh/LLMBook-zh.github.io/files/15161483/data-flow.pdf)），它展示了在线数据调度的过程：

![WechatIMG441](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/10681979/21fbcb57-46d4-429a-b2f2-c7f701e8af5a)

在线数据调度不仅能够实时处理流入的数据，还可以根据模型训练过程中的反馈进行调整，优化数据流的处理效率和质量。这种方法的主要优点包括提升数据处理的灵活性和提高模型的性能。

**Comment by leoleojie** [comment]
非常感谢您的建议，后续我们会对中文书继续进行修正。
