### ISSUE TITLE
6.3.1 错误

### ISSUE THREAD

**Issue by nanocm** [LLMBook-zh/LLMBook-zh.github.io#14]
如图，参数矩阵W按列切分得到的子矩阵列数与H行数不一致，应按行切分
![image](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/55043972/37b6c0ae-cc5d-4fda-9f7a-bb33d5bde4ec)

**Comment by StevenTang1998** [comment]
应该是HW，按列切分。非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
