### ISSUE TITLE
10.2.3 & 13.1.5 typo

### ISSUE THREAD

**Issue by nanocm** [LLMBook-zh/LLMBook-zh.github.io#16]
1）这部分表述根据上下文应该确实是“方式”，多个地方写成了“范式”
![image](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/55043972/baeacf1a-ed61-4628-bf39-0ad81b7600fd)
2）我相信这个地方要表达的是SPARQL，SPASQL至少不是一个广泛认可的术语或编程语言([SPASQL: SPARQL Support In MySQL](https://www.w3.org/2005/05/22-SPARQL-MySQL/XTech))
![image](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/55043972/59ec935a-d7ae-490f-ae3e-a0e0cdd1111c)

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，第一个我们认为“范式”更为合适，已将小标题修改；第二个我们将修改为“SPARQL”。
