### ISSUE TITLE
一段内容表达不清楚

### ISSUE THREAD

**Issue by Dhaizei** [LLMBook-zh/LLMBook-zh.github.io#18]
第122页
进一步， 谷歌的研究人员深度学习场景提出了新的半精度浮点数表示 BF16，
谷歌的研究人员深度学习场景提出了--->brain google  
或者说是在深度学习场景吧~

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
