### ISSUE TITLE
5.3节 （100页)）似有文字错误

### ISSUE THREAD

**Issue by Sumsky21** [LLMBook-zh/LLMBook-zh.github.io#2]
“进一步，解码器架构还可以细分为**三个**变种架构，包括因果解码器（CausalDecoder）架构和前缀解码器（PrefixDecoder）架构。”

这里“三个”是否应当为“两个”？
![image](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/58537872/e8f6fb69-8bbf-4058-9774-1212bd849498)

**Comment by 1190303125** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
