### ISSUE TITLE
长度惩罚（Length Penalty）的描述歧义

### ISSUE THREAD

**Issue by zYeoman** [LLMBook-zh/LLMBook-zh.github.io#20]
![image](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/9934258/e32bf5a6-9f40-4b2f-b915-469a80feff03)

长度的指数幂  $\alpha$ 显然是个大于 1 的数，如果概率除以它的话得到的结果（的绝对值）是会更小的。

研究了一下，发现实际计算是 （from [hear](https://github.com/huggingface/transformers/issues/4915)）
```
score = sum_logprobs / len(hyp) ** self.length_penalty
```

这里 sum_logprobs 是个负数，所以这个除法才能做到奖励生成更长序列的功能。希望这里描述更清晰一点。

**Comment by StevenTang1998** [comment]
非常感谢您指出这里的问题，不过不是因为负数的问题。实际上，如果是概率连乘，应该是开根号；如果是概率的负对数相加，就是我们所描述的除法。我们会优化这里的表达使其更好理解。
