### ISSUE TITLE
P34 2.2.2 Chinchilla 扩展法则：可选的还是最优的？

### ISSUE THREAD

**Issue by yucc-leon** [LLMBook-zh/LLMBook-zh.github.io#21]
<img width="697" alt="image" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/17897916/6cb14611-2902-4012-827b-35aa25c3ecec">
<img width="956" alt="image" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/17897916/ff4e8bba-29ed-4f75-9193-f8ebd3606c1d">
“可选的”这个表述在语境下至少我个人无法理解

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
