### ISSUE TITLE
【BUG】13.2.2 教育场景下的大语言模型，这一节中疑似错别字

### ISSUE THREAD

**Issue by hiwanz** [LLMBook-zh/LLMBook-zh.github.io#22]
考虑到教育领域不同学科往往具有显著的知识差异，还可以针对各学科设计专用的教育大模型。例如，
可以构建专门面向数学学科的垂域大模型，强化数学学科特有的定理公式等专业
知识，并能提供具有启发性的**结题过程**==>解题过程

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
