### ISSUE TITLE
9.2节解码加速算法

### ISSUE THREAD

**Issue by ZhangSean42** [LLMBook-zh/LLMBook-zh.github.io#24]
关于9.2节解码加速算法，有两个疑问想提出：
1.本章描述的是模型部署与推理，在模型推理中，输入应该是单个词元序列，图中的B指的是一个批次，B的值是否应该取1
2.关于访存的估计，看公式像是默认每个矩阵元素只需要访存一次，这种很高的数据重用率是否合理，毕竟标准的三重循环实现就无法做到
![image](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/153588133/4ee20fbf-ddda-4417-b937-908fba499493)

**Comment by StevenTang1998** [comment]
1. 解码过程中B并非设置为1，批量解码可以使解码效率更高，目前的绝大多数框架，例如Hugging Face和vLLM均支持该功能。
2. 访存量可能并非一次，但是肯定是对应多项式的常数次，我们使用了大O记号来表示渐进复杂度。
