### ISSUE TITLE
9.3.1 量化基础知识-P217

### ISSUE THREAD

**Issue by Mingbo-Lee** [LLMBook-zh/LLMBook-zh.github.io#25]
![image](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/51162830/23f23d02-a440-4b80-a07c-4eb0c5d3a8ac)

此处的`反应`应为`反映`。
供参考。

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
