### ISSUE TITLE
2.3.1 P23 Typo

### ISSUE THREAD

**Issue by spidercatfly** [LLMBook-zh/LLMBook-zh.github.io#27]
明细->明显
<img width="816" alt="Screen Shot 2024-06-17 at 6 06 28 PM" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/150266356/5ced7848-a6a5-48a4-95ec-d54a35fb910c">

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
