### ISSUE TITLE
Transformer架构图疑似有误

### ISSUE THREAD

**Issue by GuF-veg** [LLMBook-zh/LLMBook-zh.github.io#28]
你好呀，我刚开始入门学习llm，注意到书里84页Transformer的架构图里解码器的掩码多头注意力层和多头注意力层的残差连接好像没有画，请问这里是否有误？
<img width="560" alt="Transformer-origin" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/54523006/60f5f07b-2a0a-4b39-ab60-ea9a99fec286">
<img width="608" alt="Transformer架构图" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/54523006/96916c83-db8c-44bc-85fc-7b0a39215a74">

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
