### ISSUE TITLE
5.27式疑似缺少符号

### ISSUE THREAD

**Issue by GuF-veg** [LLMBook-zh/LLMBook-zh.github.io#29]
91页的式5.27的第二项似乎缺少了一个转置符号
<img width="936" alt="5 27" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/54523006/1299f683-129e-4cd4-82fd-cde28677c703">

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
