### ISSUE TITLE
翻译小错误

### ISSUE THREAD

**Issue by ddjwb** [LLMBook-zh/LLMBook-zh.github.io#3]
page 9:

这里标框的应该是翻译得有点问题。
<img width="682" alt="1713346397916" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/58796211/7b62b988-5aa7-47e5-83dd-8d8564770114">

**Comment by StevenTang1998** [comment]
非常感谢您的指出，数据课程的定义详见第4.4.2节，我们会将这句话修正为“需要 设计 有效的数据配比与数据课程”。
