### ISSUE TITLE
10.1基础提示例10.4内容有误

### ISSUE THREAD

**Issue by bogan-FMA** [LLMBook-zh/LLMBook-zh.github.io#31]
![image](https://github.com/user-attachments/assets/baedb63b-a2b8-4b65-b9d4-8c80438c44f6)

“让我们一步一步地思考” 应该是在“用户输入”中。

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
