### ISSUE TITLE
疑似几处笔误

### ISSUE THREAD

**Issue by JianzhouZhan** [LLMBook-zh/LLMBook-zh.github.io#32]
<img width="589" alt="image" src="https://github.com/user-attachments/assets/3c22f713-af3e-43a6-b2ec-19838bcbe426">

无关甚可能有害的数据 -> 无关甚"至"可能有害的数据

<img width="908" alt="image" src="https://github.com/user-attachments/assets/f24f0a1c-ea25-4f0e-9163-75e53a50a79c">

所对应的 -> 所对应的"位置"  或者 所对应的 -> 对应

<img width="769" alt="image" src="https://github.com/user-attachments/assets/b28cd680-74c4-4145-a171-74d4de4308c6">

这里描述不太顺畅

<img width="810" alt="image" src="https://github.com/user-attachments/assets/40cad740-0810-41f6-b511-5c2ac257fe15">

这里"因此"是否为"依次"

<img width="769" alt="image" src="https://github.com/user-attachments/assets/32df6fd8-672d-4a5b-9646-92520f4e040e">

少了些修饰, 是否为"扩展"至

<img width="776" alt="image" src="https://github.com/user-attachments/assets/f58a30be-731b-48ff-a21a-1519f5e3955d">

"累和" 是否为"求和" or “累加"

<img width="786" alt="image" src="https://github.com/user-attachments/assets/93125ca9-016c-4b9a-aba9-71cd11e5141d">

都与预训练保持阶段一致  -> 都与预训练阶段保持一致

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
