### ISSUE TITLE
8.2.4 强化学习训练中，公式8.6似乎有误

### ISSUE THREAD

**Issue by viclin0624** [LLMBook-zh/LLMBook-zh.github.io#33]
<img width="734" alt="image" src="https://github.com/user-attachments/assets/b9f999ef-72e8-4604-b728-bca3505749c5">
如上图所示，似乎最大化累计奖励的期望值不需要argmax；同时，若有argmax，公式8.7的求梯度则与公式8.6不符，烦请确认一下

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
