### ISSUE TITLE
第五章 文字和句子疑似语法错误

### ISSUE THREAD

**Issue by zouzihan3** [LLMBook-zh/LLMBook-zh.github.io#35]
![Snipaste_2024-09-03_16-05-26](https://github.com/user-attachments/assets/cbdda53f-262c-4ce1-a58f-6fe10fc6f3e8)

疑似为“其性能超越了更成熟、规模更大的LLaMA-2（70B）”

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
