### ISSUE TITLE
关于Adam优化器显存占用的疑问

### ISSUE THREAD

**Issue by AlphaTok-sg** [LLMBook-zh/LLMBook-zh.github.io#37]
我看到书中讲Adam 或 AdamW优化器则需要额外存储 32 位浮点数的模型参数、动量参数以及动量二阶矩参数。但是我同样看到huggingface的blog在计算优化器显存占用只算了动量参数以及动量二阶矩参数：https://huggingface.co/blog/zh/dpo_vlm

请问Adam优化器中包不包含模型参数

**Comment by StevenTang1998** [comment]
建议阅读更为官方的论文《ZeRO: Memory Optimizations Toward Training Trillion Parameter Models》，其中的3.1节中进行了说明，在混合精度训练中，Adam需要包含32位的模型副本。
