### ISSUE TITLE
第二章一处公式的补充

### ISSUE THREAD

**Issue by dream-tentacle** [LLMBook-zh/LLMBook-zh.github.io#5]
在2.2.1 KM扩展法则中的公式(2.1)中，有三个量$`N_c, D_c, C_c`$，这三个量在文中的解释是“分别表示非嵌入参数数量、训练数据数量和实际的算力开销”，个人认为这个说明并不清楚。在原英文论文中，虽然也没有具体介绍其含义，但说明了其“precise numerical values”取决于“vocabulary size and tokenization”，且“do not have a fundamental meaning”。个人认为可以将“分别表示非嵌入参数数量、训练数据数量和实际的算力开销”改为“分别是实验性的常数数值，对应于非嵌入参数数量、训练数据数量和实际的算力开销“，会更加清晰易懂，不容易引起歧义。

**Comment by LLMBook-zh** [comment]
非常感谢您的建议，我们已经对上述内容进行了改正。
