### ISSUE TITLE
第一章表述问题

### ISSUE THREAD

**Issue by nanocm** [LLMBook-zh/LLMBook-zh.github.io#7]
首先非常感谢你们出了这样一本书，除了书中引用过的LLM-TAP，这是我见过的第二本有关LLM并且内容非常丰富的书籍。
下面是我在第一章中遇到的一些可能的表述错误
<img width="885" alt="Snipaste_2024-04-28_15-01-07" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/55043972/123bfc0a-4bc6-4682-985d-65f4b7add880">
<img width="931" alt="Snipaste_2024-04-28_15-01-32" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/55043972/adfcf9e8-9f01-4f66-83bc-fbfb1fae39b4">
<img width="820" alt="Snipaste_2024-04-28_15-01-47" src="https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/55043972/89b75dc2-f2d8-43c3-af32-2eb2255e6745">

**Comment by StevenTang1998** [comment]
非常感谢您指出书中的错误，我们已经对上述错误内容进行了改正。
