### ISSUE TITLE
9.2.3推测解码__一点小建议

### ISSUE THREAD

**Issue by corny813** [LLMBook-zh/LLMBook-zh.github.io#8]
中文中的“单词”概念与英文中的“word”有所不同，中文更多的是以字为基本单位。这里感觉用字表述更好，而不是“单词”，可能是word直译了
![image](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/4627442/d6427f91-9523-4681-92ba-e56d99d7b6ca)

然后是例子的第二步：{{{第二步，再使用小模型生成 3 个单词，假设结果为“日子是”，大模型验证第一个词便发现错误，同时将其修正为“他”;}}}

output=忘记的是他的背影，第二步为"是他"

祝好！

**Comment by StevenTang1998** [comment]
非常感谢您的建议，第一个问题我们会将其修正为“词元”；第二个问题我们会修改例子。
