### ISSUE TITLE
9.3.1量化基础知识__一点计算错误

### ISSUE THREAD

**Issue by corny813** [LLMBook-zh/LLMBook-zh.github.io#9]
![image](https://github.com/LLMBook-zh/LLMBook-zh.github.io/assets/4627442/5736ae9d-8b44-4fbc-a358-b6e98a507126)

二元一次方程解出来S是正数，1.2也是正数，所以Z>128

x_q最小值应该是对应的量化区间最小值，整数范围为 [−128, 127]的话，最小值应该为-128

祝好！

**Comment by lpyhdzx** [comment]
感谢您提出的问题。这部分计算例子中，为了有更低的量化误差，选择取整操作为四舍五入取整，同时还需要考虑超出[-128,127]范围时候需要做必要的截断。因此，在这种情况下，x_q=1.2/0.0486 约等于25，再加上-152，等于-127，这时反量化则为1.2157。如果下向下取整，则x_q=1.2/0.0486对应24，再加上-152等于-128，反量化为1.1671，相比较1.2157带来的量化误差更大。
